# Generated by Django 2.1.2 on 2018-11-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0003_auto_20181123_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='autor',
            new_name='author',
        ),
    ]
