# Generated by Django 2.1.2 on 2018-11-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0004_auto_20181123_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['create']},
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'ordering': ['-create']},
        ),
    ]
