# Generated by Django 2.1.2 on 2018-12-02 09:08

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('entradas', '0005_auto_20181127_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
