"""
Django settings for webDe project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from django.urls import reverse_lazy

try:
    from .LocalSetting import *
    DEBUG = True
    ALLOWED_HOSTS = ['*']
except:
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True
    ALLOWED_HOSTS = ['*']

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =')z(66-zt@g3y_=mh(n(xs8!es%yi0f7aczob9m&m)xikyrx#*6'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

#ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.accounts',
    'apps.entradas',
    #'social_django',
    'taggit',
    'sslserver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webDe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'webDe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticRoot')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL ='/media/'

#Social Media Login
AUTHENTICATION_BACKENDS = (
#    'social_core.backends.amazon.AmazonOAuth2',
#   # 'social_core.backends.bitbucket.BitbucketOAuth',
   # 'social_core.backends.facebook.FacebookAppOAuth2',
   # 'social_core.backends.facebook.FacebookOAuth2',
#    'social_core.backends.github.GithubOAuth2',
#    'social_core.backends.gitlab.GitLabOAuth2',
#    'social_core.backends.google.GoogleOAuth',
   # 'social_core.backends.google.GoogleOAuth2',
#    'social_core.backends.google.GoogleOpenId',
#    'social_core.backends.google.GooglePlusAuth',
#    'social_core.backends.google_openidconnect.GoogleOpenIdConnect',
#    'social_core.backends.instagram.InstagramOAuth2',
#    'social_core.backends.linkedin.LinkedinOAuth',
#    'social_core.backends.linkedin.LinkedinOAuth2',
#    'social_core.backends.spotify.SpotifyOAuth2',
#    'social_core.backends.trello.TrelloOAuth',
#    'social_core.backends.tumblr.TumblrOAuth',
#    'social_core.backends.twitter.TwitterOAuth',
#    'social_core.backends.yahoo.YahooOAuth',
#    'social_core.backends.yahoo.YahooOpenId',
    'django.contrib.auth.backends.ModelBackend',
)

#Para esto hay que tenerlo con https la redireccion
#SOCIAL_AUTH_FACEBOOK_KEY = FACEBOOK_KEY
#SOCIAL_AUTH_FACEBOOK_SECRET = FACEBOOK_SECRET
#para traer el email
#SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
#SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
#    'fields': 'id,name,email',
#}

#SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = GOOGLE_KEY
#SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = GOOGLE_SECRET
#SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True


#SOCIAL_AUTH_PIPELINE = (
    #revisar para implementar que nose repitan los email
#    'utilsSocialPipe.check_email_exists',
#    'social_core.pipeline.social_auth.social_details',
#    'social_core.pipeline.social_auth.social_uid',
#    'social_core.pipeline.social_auth.auth_allowed',
#    'social_core.pipeline.social_auth.social_user',
#    'social_core.pipeline.user.get_username',
#    'social_core.pipeline.mail.mail_validation',
#    'social_core.pipeline.user.create_user',
#    'social_core.pipeline.social_auth.associate_user',
#    'social_core.pipeline.debug.debug',
#    'social_core.pipeline.social_auth.load_extra_data',
#    'social_core.pipeline.user.user_details',
#    'social_core.pipeline.debug.debug'
#)


#Login opcions
#LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = reverse_lazy('accounts:login')
LOGIN_REDIRECT_URL = reverse_lazy('entradas:index')

#SSL
SECURE_SSL_REDIRECT = True
CSRF_COOKIE_SECURE = True

#config file
FILE_UPLOAD_PERMISSIONS = 0o644
